### ISSUE TITLE
Convert character and dungeon assets to 32x32 (rpg dungeon & monster pack)

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/modite-adventure#9]
All sprites need to be doubled (32x32) with the following rules:

## Tasks (See example below)
__(For each character)__ 
- [ ] Create a 256x704 windows bitmapped image in `src/resources/sprites/`
- [ ] Set background to `#FF00FF`
- [ ] Double sprite size
- [ ] Flush sprites to top-left of the a 64x64 boundary (characters only)
- [ ] *Lightly* modify any sprites that may go beyond the 64x64 boundary

__(For each dungeon asset)__
- [ ] Double sprite size
- [ ] Set background to `#FF00FF`
- [ ] Save as windows bitmapped image in `src/resources/sprites/`

#### rpg-monster-pack v1.0
- chara_hero.png
- chara_slime.png
- tiles_dungeon.png (tiles for dungeons)

#### rpg-monster-pack v1.0
- chara_bat.png
- chara_goblin.png
- chara_goblin_sniper.png
- chara_orc.png
- chara_rat.png
- chara_slime.png
- chara_spider.png
- chara_troll.png
- projectile_arrow.png

** SOURCE **
![chara_hero](https://user-images.githubusercontent.com/180031/61647273-010b8d80-ac7b-11e9-96fc-f4fd9415e00d.png)

** OUTPUT **
![image](https://user-images.githubusercontent.com/180031/61647256-f6e98f00-ac7a-11e9-86ba-9784b8f663e9.png)
